name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build_type: [Release]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Fetch & Reset
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fdx  # Xóa file không cần thiết

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B build \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.build_type }} --target all

      - name: Test
        working-directory: build
        shell: bash
        run: ctest --build-config ${{ matrix.build_type }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Fetch & Reset
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fdx

      - name: Clean and Build
        run: |
          rm -rf build/ CMakeCache.txt CMakeFiles/

          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release

          cmake --build build --target all
          
          mkdir -p bin
          cp build/MyExecutable bin/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: bin/MyExecutable
          retention-days: 5
