name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Các bước dành cho Windows
      - name: Git Pull (Windows)
        if: matrix.os == 'windows-latest'
        run: git pull origin main
        shell: cmd

      - name: Clean previous builds (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          rmdir /S /Q "${{ github.workspace }}\\build"
          git clean -ffdx
        shell: cmd

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmake -B "${{ github.workspace }}\\build" ^
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} ^
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} ^
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        shell: cmd

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build "${{ github.workspace }}\\build" --config ${{ matrix.build_type }}
        shell: cmd

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: "${{ github.workspace }}\\build"
        run: ctest --build-config ${{ matrix.build_type }}
        shell: cmd

      # Các bước dành cho Unix (Ubuntu, macOS)
      - name: Git Pull (Unix)
        if: matrix.os != 'windows-latest'
        run: git pull origin main
        shell: bash

      - name: Clean previous builds (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          rm -rf "${{ github.workspace }}/build"
          git clean -ffdx
        shell: bash

      - name: Configure CMake (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cmake -B "${{ github.workspace }}/build" \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        shell: bash

      - name: Build (Unix)
        if: matrix.os != 'windows-latest'
        run: cmake --build "${{ github.workspace }}/build"
        shell: bash

      - name: Test (Unix)
        if: matrix.os != 'windows-latest'
        working-directory: "${{ github.workspace }}/build"
        run: ctest
        shell: bash
