name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            shell: bash
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            shell: cmd
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            shell: bash

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Configure CMake
      shell: ${{ matrix.shell }}
      run: |
        cmake -B build \
              -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
              -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      shell: ${{ matrix.shell }}
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build
      shell: ${{ matrix.shell }}
      run: ctest --build-config ${{ matrix.build_type }}

  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Fetch & Reset
        run: |
          git fetch origin main
          git reset --hard origin/main
          git clean -fdx
          git pull origin main

      - name: Clean and Build
        run: |
          # Xóa thư mục build và cache cũ
          rm -rf build/
          rm -rf CMakeCache.txt
          rm -rf CMakeFiles/
          
          # Tạo build mới
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release
          
          # Build project
          cmake --build build
          
          # Tạo thư mục bin và copy executable
          mkdir -p bin
          cp build/MyExecutable bin/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: bin/MyExecutable
          retention-days: 5  # Thêm thời gian lưu trữ artifact