name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Giá trị mặc định sẽ được ghi đè bởi phần include
        os: [macos-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Pull
        run: git pull origin main
        shell: bash

      - name: Clean previous builds
        run: |
          rm -rf "${{ github.workspace }}/build"
          git clean -ffdx
        shell: bash

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B "${{ github.workspace }}/build" \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      # Build bước riêng cho Unix (Ubuntu, macOS) không sử dụng --config
      - name: Build (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: cmake --build "${{ github.workspace }}/build"

      # Build bước riêng cho Windows sử dụng --config
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: cmake --build "%GITHUB_WORKSPACE%\build" --config ${{ matrix.build_type }}

      # Test bước riêng cho Unix: không sử dụng --build-config
      - name: Test (Unix)
        if: matrix.os != 'windows-latest'
        working-directory: "${{ github.workspace }}/build"
        shell: bash
        run: ctest

      # Test bước riêng cho Windows: sử dụng --build-config nếu cần
      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: "%GITHUB_WORKSPACE%\build"
        shell: cmd
        run: ctest --build-config ${{ matrix.build_type }}
